Repository tide-app/tide, pull requests merged in 2020-12, with the labels that each got.

#259 close #147 by adding a search shortcut activated with Slash key
  src/Nav.js
Labels: enhancement, p2

#254 highlight selected sound in soundlist
  src/Sound.js
  src/SoundList.js
Labels: p0

#266 fix alignment of homepage banner on small screens
  src/App.js
Labels: UI, accessibility
