Repository tide-app/tide, pull requests merged in 2020-10, with the labels that each got.

#81 Pre commit checks
  package.json
  yarn.lock
Labels: enhancement, infra

#92 hide crop, download and play/pause buttons while sound loads to close #89
  cypress/plugins/index.js
  src/Sound.js
Labels: enhancement, good first issue

#87 Sound title and Description redesigned
  src/Sound.js
  src/styles.css
  src/tailwind.css
Labels: good first issue

#90 Download button fix
  .npmrc
  README.md
  package.json
  public/icons/android-chrome-192x192.png
  public/icons/android-chrome-512x512.png
  public/icons/apple-touch-icon.png
  public/icons/browserconfig.xml
  public/icons/favicon-16x16.png
  public/icons/favicon-32x32.png
  public/icons/favicon.ico
  public/icons/icon-128x128.png
  public/icons/icon-144x144.png
  public/icons/icon-152x152.png
  public/icons/icon-192x192.png
  public/icons/icon-384x384.png
  public/icons/icon-512x512.png
  public/icons/icon-72x72.png
  public/icons/icon-96x96.png
  public/icons/icon.svg
  public/icons/mstile-144x144.png
  public/icons/mstile-150x150.png
  public/icons/mstile-310x150.png
  public/icons/mstile-310x310.png
  public/icons/mstile-70x70.png
  public/icons/safari-pinned-tab.svg
  public/icons/site.webmanifest
  public/index.html
  public/manifest.json
  src/Sound.js
  src/SoundList.js
  src/styles.css
  src/tailwind.css
  yarn.lock
Labels: good first issue

#98 close #96 by adding day and night theme images to README.md
  README.md
  screenshots/Homepage-Day-Theme-2020-10-10-at-7.21.57-PM.png
  screenshots/Homepage-Night-Theme-2020-10-10-at-7.11.41-PM.png
  screenshots/Soundpage-Day-Theme-2020-10-10-at-7.20.07-PM.png
  screenshots/Soundpage-Night-Theme-2020-10-10-at-7.17.51-PM.png
Labels: documentation, enhancement, good first issue
